wandb_version: 1

learning_rate:
  desc: null
  value: 0.0025
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.17.8
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724981984
    t:
      1:
      - 2
      - 3
      - 5
      - 49
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 49
      - 53
      - 55
      3:
      - 3
      - 8
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.17.8
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      - 17
      13: windows-amd64
